os: osx
virtualenv:
    system_site_packages: true
language: python
python:
  - "2.7"
  #python 3 not yet supported
  #- "3.2"
  #- "3.3"
  #- "3.4"
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq python-numpy python-scipy
install:
  - pip install -r requirements.txt
# command to run tests
script: python cmm.py
